(function(){
'use strict';
const cfg=window.ESTUDOS_SUPABASE_CONFIG||{},$=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const client=window.supabase?.createClient&&cfg.url&&cfg.publishableKey?window.supabase.createClient(cfg.url,cfg.publishableKey):null;
let ready=false;
async function guard(){if(!client)return false;const {data:{user}}=await client.auth.getUser();if(!user)return false;const {data:isAdmin,error}=await client.rpc('is_current_user_admin');return !error&&Boolean(isAdmin)}
async function eventCount(name,since){const {count,error}=await client.from('product_events').select('*',{count:'exact',head:true}).eq('event_name',name).gte('created_at',since);if(error)throw error;return count||0}
function funnelCard(label,value,note){return `<div class="v2-funnel-card"><span>${esc(label)}</span><b>${Number(value||0).toLocaleString('pt-BR')}</b><small>${esc(note)}</small></div>`}
async function loadProduct(){if(!ready)return;const host=$('v2ProductFunnel');if(!host)return;host.textContent='Carregando…';const since=new Date(Date.now()-7*86400000).toISOString();try{const [landing,start,appOpen,diagStart,diagDone,answers]=await Promise.all(['landing_open','landing_start','app_open','diagnostic_started','diagnostic_completed','question_answered'].map(x=>eventCount(x,since)));const conversion=landing?Math.round(start/landing*100):0,activation=start?Math.round(appOpen/start*100):0,diagRate=diagStart?Math.round(diagDone/diagStart*100):0;host.innerHTML=[funnelCard('Visitas',landing,'landing aberta'),funnelCard('Começaram',start,`${conversion}% das visitas`),funnelCard('Abriram o app',appOpen,`${activation}% dos cliques`),funnelCard('Diagnósticos',diagDone,`${diagRate}% concluídos`),funnelCard('Respostas',answers,'questões respondidas')].join('');const meta=$('v2ProductMeta');if(meta)meta.textContent=`Últimos 7 dias · métricas anônimas · atualizado ${new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}`}catch(e){host.textContent='Não foi possível carregar as métricas: '+e.message}}
function reportActions(r){if(r.status==='resolvido'||r.status==='descartado')return `<div class="v2-report-actions"><button data-report-status="revisando" data-report-id="${r.id}">Reabrir</button><button data-open-question="${esc(r.question_id)}">Ver questão</button></div>`;return `<div class="v2-report-actions"><button data-open-question="${esc(r.question_id)}">Ver questão</button><button data-report-status="revisando" data-report-id="${r.id}">Revisando</button><button class="primary" data-report-status="resolvido" data-report-id="${r.id}">Resolver</button><button class="danger" data-report-status="descartado" data-report-id="${r.id}">Descartar</button></div>`}
async function loadReports(){if(!ready)return;const host=$('v2Reports');if(!host)return;host.textContent='Carregando…';try{const {data,error}=await client.from('question_reports').select('id,created_at,question_id,reason,detail,exam,module,status').order('created_at',{ascending:false}).limit(100);if(error)throw error;const rows=data||[],open=rows.filter(r=>!['resolvido','descartado'].includes(r.status));const m=$('mCustom'),h=$('hAlerts'),meta=$('v2ReportsMeta');if(m)m.textContent=open.length;if(h)h.textContent=open.length;if(meta)meta.textContent=`${open.length} pendente(s) · ${rows.length} relato(s) recente(s)`;host.innerHTML=rows.map(r=>`<div class="v2-report"><div><b>${esc(r.question_id)}</b><span>${esc(r.exam)}${r.module?' · M'+esc(r.module):''}</span></div><div><span>${new Date(r.created_at).toLocaleString('pt-BR')}</span><span class="v2-status ${esc(r.status)}">${esc(r.status)}</span></div><div><b>${esc(r.reason)}</b><small>${esc(r.detail||'Sem comentário adicional.')}</small></div>${reportActions(r)}</div>`).join('')||'<p class="muted">Nenhum relato recebido.</p>'}catch(e){host.textContent='Não foi possível carregar os relatos: '+e.message}}
async function updateReport(id,status){const patch={status,resolved_at:['resolvido','descartado'].includes(status)?new Date().toISOString():null};const {error}=await client.from('question_reports').update(patch).eq('id',Number(id));if(error)return alert(error.message);await loadReports()}
async function openQuestion(id){const {data,error}=await client.from('questions').select('*').eq('id',id).maybeSingle();if(error||!data)return alert(error?.message||'Questão não encontrada.');const btn=[...document.querySelectorAll('#table [data-edit]')].find(x=>x.dataset.edit===String(id));if(btn){btn.click();return}const search=$('search');if(search){search.value=id;search.dispatchEvent(new Event('input',{bubbles:true}));setTimeout(()=>{const b=[...document.querySelectorAll('#table [data-edit]')].find(x=>x.dataset.edit===String(id));b?.click()},350)}}
async function loadVersion(){if(!ready)return;try{const {data}=await client.from('app_meta').select('key,value').in('key',['app_version','question_bank_version']);const map=Object.fromEntries((data||[]).map(x=>[x.key,x.value]));if($('v6ServerVersion'))$('v6ServerVersion').textContent=map.app_version||'2.0.0';const meta=$('editorialMeta');if(meta&&map.question_bank_version)meta.title='Banco: '+map.question_bank_version}catch{}}
async function loadFamilies(){if(!ready)return;try{const {data}=await client.from('questions').select('variant_family').eq('editorial_status','publicada').limit(10000);const n=new Set((data||[]).map(x=>x.variant_family).filter(Boolean)).size;if($('hFamilies'))$('hFamilies').textContent=n.toLocaleString('pt-BR')}catch{}}
async function init(){ready=await guard();if(!ready)return;const reports=$('v2Reports');reports?.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.reportStatus)updateReport(b.dataset.reportId,b.dataset.reportStatus);else if(b.dataset.openQuestion)openQuestion(b.dataset.openQuestion)});$('v2RefreshReports')?.addEventListener('click',loadReports);$('v2RefreshProduct')?.addEventListener('click',loadProduct);await Promise.all([loadVersion(),loadFamilies(),loadReports(),loadProduct()])}
setTimeout(init,450);
})();
