(function(){
'use strict';
const V='2.0.0',cfg=window.ESTUDOS_SUPABASE_CONFIG||{},CLASSROOM_VERSION='1.0.0';
const DIAG_KEY='gplus_v2_diagnostic_done',ANON_KEY='gplus_v2_anon_id';
let reportQuestion=null,lastPage='',lastPageAt=0;
const safeParse=(raw,fallback)=>{try{return JSON.parse(raw)}catch{return fallback}};
function anonId(){let id=localStorage.getItem(ANON_KEY);if(id)return id;id='anon_'+(crypto?.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2));localStorage.setItem(ANON_KEY,id);return id}
function context(){const exam=app?.settings?.focusExam==='PISM'?'PISM':'ENEM';return{exam,module:exam==='PISM'?(app?.settings?.pismModule||'I'):null}}
function restHeaders(){return{apikey:cfg.publishableKey,authorization:`Bearer ${cfg.publishableKey}`,'content-type':'application/json',prefer:'return=minimal'}}
async function post(table,payload){if(!cfg.url||!cfg.publishableKey)return false;try{const r=await fetch(`${String(cfg.url).replace(/\/$/,'')}/rest/v1/${table}`,{method:'POST',headers:restHeaders(),body:JSON.stringify(payload),keepalive:true});return r.ok}catch{return false}}
function track(eventName,{page=null,questionId=null,metadata={}}={}){const c=context();const clean={};for(const [k,v] of Object.entries(metadata||{})){if(['string','number','boolean'].includes(typeof v)||v===null)clean[k]=v}void post('product_events',{anonymous_id:anonId(),event_name:String(eventName).slice(0,64),page:page?String(page).slice(0,64):null,exam:c.exam,module:c.module,question_id:questionId?String(questionId).slice(0,128):null,metadata:clean})}
function toastSafe(text){if(typeof window.toast==='function')window.toast(text);else console.info('[Gabarito+]',text)}
function totalAttempts(){const stats=safeParse(localStorage.getItem('study_question_stats_v2')||'{}',{});return Object.values(stats||{}).reduce((n,x)=>n+Number(x?.attempts||0),0)}
function diagnosticDone(){if(localStorage.getItem(DIAG_KEY))return true;if(totalAttempts()>=20){localStorage.setItem(DIAG_KEY,JSON.stringify({source:'existing-data',at:new Date().toISOString()}));return true}return false}
function diagnosticScore(q){let s=0;const source=String(q.source||'').toLowerCase(),type=String(q.variantType||'').toLowerCase();if(source.includes('matriz enem')||source.includes('programa pism'))s+=80;if(type.includes('autoral'))s+=35;if(q.difficulty==='Médio')s+=14;if(q.difficulty==='Difícil')s+=5;s+=Math.random()*8;return s}
function diagnosticPool(){const c=context();let pool=QUESTIONS.filter(q=>q.exam===c.exam&&(c.exam!=='PISM'||String(q.module)===String(c.module)));pool=[...pool].sort((a,b)=>diagnosticScore(b)-diagnosticScore(a));const usedFamilies=new Set(),usedSubjects=new Set(),picked=[];for(const q of pool){const family=String(q.variantFamily||q.id);if(usedFamilies.has(family)||usedSubjects.has(q.subject))continue;picked.push(q);usedFamilies.add(family);usedSubjects.add(q.subject);if(picked.length===10)break}if(picked.length<10){for(const q of pool){const family=String(q.variantFamily||q.id);if(usedFamilies.has(family))continue;picked.push(q);usedFamilies.add(family);if(picked.length===10)break}}return picked}
function diagnosticCard(){const host=document.getElementById('v39Home');if(!host)return;document.getElementById('gplusV2Diagnostic')?.remove();if(diagnosticDone())return;const active=app?.v27Drill?.mode==='diagnostic';const el=document.createElement('section');el.id='gplusV2Diagnostic';el.className='gplus-v2-diagnostic';el.innerHTML=`<div class="gplus-v2-diagnostic-copy"><span class="gplus-v2-diagnostic-kicker">Diagnóstico inicial</span><h3>${active?'Continue calibrando seu radar.':'Calibre seu radar em 10 questões.'}</h3><p>${active?'Retome do ponto em que parou.':'Um bloco curto para o Gabarito+ descobrir onde sua preparação pode ganhar mais pontos.'}</p><div class="gplus-v2-diagnostic-meta"><span>10 questões</span><span>≈ 15–20 min</span><span>${context().exam}${context().exam==='PISM'?' · Módulo '+context().module:''}</span></div></div><div class="gplus-v2-diagnostic-actions"><button type="button" class="btn btn-primary" id="gplusV2DiagnosticBtn">${active?'Continuar':'Iniciar diagnóstico'}</button></div>`;const hero=host.querySelector('.v39-hero');hero?.insertAdjacentElement('afterend',el)||host.prepend(el);el.querySelector('#gplusV2DiagnosticBtn')?.addEventListener('click',startDiagnostic)}
function startDiagnostic(){if(app?.v27Drill?.mode==='diagnostic'&&app.currentQuestion){go('questions');renderQuestion();return}const pool=diagnosticPool();if(pool.length<5){toastSafe('Ainda não há questões suficientes para esse diagnóstico.');return}app.mock=null;app.v25Review=null;app.v27Drill={ids:pool.map(q=>q.id),index:0,minutes:20,mode:'diagnostic',started:Date.now(),correct:0};app.currentQuestion=pool[0];track('diagnostic_started',{metadata:{questions:pool.length}});go('questions');renderQuestion();toastSafe(`Diagnóstico iniciado · ${pool.length} questões`)}
function reportModal(){if(document.getElementById('gplusV2ReportModal'))return;const el=document.createElement('div');el.id='gplusV2ReportModal';el.className='gplus-v2-modal';el.hidden=true;el.setAttribute('role','dialog');el.setAttribute('aria-modal','true');el.setAttribute('aria-labelledby','gplusV2ReportTitle');el.innerHTML=`<div class="gplus-v2-modal-card"><div class="gplus-v2-modal-head"><div><h3 id="gplusV2ReportTitle">Reportar questão</h3><p id="gplusV2ReportQuestion">Ajude a manter o banco confiável.</p></div><button type="button" class="gplus-v2-modal-close" id="gplusV2ReportClose" aria-label="Fechar">×</button></div><form id="gplusV2ReportForm"><div class="gplus-v2-modal-body"><div class="gplus-v2-field"><label for="gplusV2Reason">O que precisa ser revisto?</label><select id="gplusV2Reason"><option value="gabarito">Gabarito</option><option value="enunciado">Enunciado</option><option value="alternativas">Alternativas</option><option value="explicacao">Explicação</option><option value="conteudo">Conteúdo / assunto</option><option value="outro">Outro</option></select></div><div class="gplus-v2-field"><label for="gplusV2Detail">Detalhe (opcional)</label><textarea id="gplusV2Detail" maxlength="500" placeholder="Explique brevemente o problema encontrado."></textarea></div><div class="gplus-v2-privacy-note">Envie apenas informações sobre a questão. Não inclua nome, e-mail, telefone ou outros dados pessoais.</div><div class="gplus-v2-report-status" id="gplusV2ReportStatus"></div></div><div class="gplus-v2-modal-actions"><button type="button" class="btn btn-secondary" id="gplusV2ReportCancel">Cancelar</button><button type="submit" class="btn btn-primary" id="gplusV2ReportSubmit">Enviar para revisão</button></div></form></div>`;document.body.appendChild(el);const close=()=>{el.hidden=true;document.body.style.overflow=''};el.querySelector('#gplusV2ReportClose').addEventListener('click',close);el.querySelector('#gplusV2ReportCancel').addEventListener('click',close);el.addEventListener('click',e=>{if(e.target===el)close()});el.querySelector('#gplusV2ReportForm').addEventListener('submit',submitReport)}
function openReport(){reportQuestion=app?.currentQuestion||null;if(!reportQuestion){toastSafe('Abra uma questão antes de reportar.');return}reportModal();const m=document.getElementById('gplusV2ReportModal'),st=document.getElementById('gplusV2ReportStatus');document.getElementById('gplusV2ReportQuestion').textContent=`Questão ${reportQuestion.id} · ${reportQuestion.subject||''}`;document.getElementById('gplusV2Detail').value='';document.getElementById('gplusV2Reason').value='gabarito';st.textContent='';st.dataset.state='';m.hidden=false;document.body.style.overflow='hidden';document.getElementById('gplusV2Reason').focus()}
async function submitReport(ev){ev.preventDefault();if(!reportQuestion)return;const btn=document.getElementById('gplusV2ReportSubmit'),st=document.getElementById('gplusV2ReportStatus'),reason=document.getElementById('gplusV2Reason').value,detail=document.getElementById('gplusV2Detail').value.trim().slice(0,500);btn.disabled=true;st.textContent='Enviando…';st.dataset.state='';const ok=await post('question_reports',{anonymous_id:anonId(),question_id:String(reportQuestion.id),reason,detail:detail||null,exam:reportQuestion.exam,module:reportQuestion.exam==='PISM'?(reportQuestion.module||null):null,status:'novo'});btn.disabled=false;if(!ok){st.textContent='Não foi possível enviar agora. Tente novamente.';st.dataset.state='error';return}localStorage.setItem(`gplus_v2_reported_${reportQuestion.id}`,new Date().toISOString());track('question_reported',{questionId:reportQuestion.id,metadata:{reason}});st.textContent='Recebido. Essa questão entrou na fila editorial.';st.dataset.state='ok';setTimeout(()=>{const m=document.getElementById('gplusV2ReportModal');if(m){m.hidden=true;document.body.style.overflow=''}},900)}
function addReportButton(){const card=document.getElementById('questionCard');if(!card)return;const toolbar=card.querySelector('.q-toolbar');if(!toolbar||toolbar.querySelector('.gplus-v2-report-btn'))return;const direct=[...toolbar.children].filter(x=>x.tagName==='DIV'),actions=direct.at(-1)||toolbar;const b=document.createElement('button');b.type='button';b.className='btn btn-ghost btn-sm gplus-v2-report-btn';b.textContent='Reportar';b.addEventListener('click',openReport);actions.prepend(b)}
function versionBadge(){const foot=document.querySelector('.sidebar-foot');if(!foot||foot.querySelector('.gplus-v2-version'))return;const b=document.createElement('span');b.className='gplus-v2-version';b.textContent='V2.0';foot.appendChild(b)}
function loadClassrooms(){if(!document.querySelector('link[data-gplus-classrooms]')){const l=document.createElement('link');l.rel='stylesheet';l.href=`/assets/classrooms-v1.css?v=${CLASSROOM_VERSION}`;l.dataset.gplusClassrooms='1';document.head.appendChild(l)}if(!document.querySelector('script[data-gplus-classrooms]')){const s=document.createElement('script');s.src=`/js/classrooms-v1.js?v=${CLASSROOM_VERSION}`;s.defer=true;s.dataset.gplusClassrooms='1';document.head.appendChild(s)}}
function instrument(){if(window.go&&!window.go.__gplusV2){const base=window.go;const wrapped=function(page,...args){const now=Date.now();if(page!==lastPage||now-lastPageAt>1200){lastPage=page;lastPageAt=now;track('page_view',{page})}const r=base.call(this,page,...args);setTimeout(()=>{diagnosticCard();addReportButton()},30);return r};wrapped.__gplusV2=true;window.go=wrapped}
 if(window.answerQuestion&&!window.answerQuestion.__gplusV2){const base=window.answerQuestion;const wrapped=function(id,index,...args){const q=QUESTIONS.find(x=>String(x.id)===String(id));const ok=q?Number(index)===Number(q.answer):null;const r=base.call(this,id,index,...args);track('question_answered',{page:'questions',questionId:id,metadata:{correct:ok,subject:q?.subject||null,topic:q?.topic||null,mode:app?.v27Drill?.mode||app?.mock?'session':'practice'}});setTimeout(addReportButton,20);return r};wrapped.__gplusV2=true;window.answerQuestion=wrapped}
 if(window.openOnboarding&&!window.openOnboarding.__gplusV2){const base=window.openOnboarding;const wrapped=function(...args){const r=base.apply(this,args);setTimeout(()=>{if(document.getElementById('v37Onboarding')?.classList.contains('open'))track('onboarding_opened',{page:'home'})},0);return r};wrapped.__gplusV2=true;window.openOnboarding=wrapped}
 if(window.onboardingNext&&!window.onboardingNext.__gplusV2){const base=window.onboardingNext;const wrapped=function(...args){const modal=document.getElementById('v37Onboarding'),was=modal?.classList.contains('open');const r=base.apply(this,args);setTimeout(()=>{if(was&&!modal?.classList.contains('open')){track('onboarding_completed',{page:'home'});diagnosticCard()}},0);return r};wrapped.__gplusV2=true;window.onboardingNext=wrapped}
 if(window.v27NextDrill&&!window.v27NextDrill.__gplusV2){const base=window.v27NextDrill;const wrapped=function(...args){const d=app?.v27Drill,isDiag=d?.mode==='diagnostic',isLast=isDiag&&d.index>=d.ids.length-1,result=isDiag?{questions:d.ids.length,correct:Number(d.correct||0),started:d.started}:null;const r=base.apply(this,args);if(isLast){const pct=Math.round((result.correct/Math.max(1,result.questions))*100);localStorage.setItem(DIAG_KEY,JSON.stringify({completedAt:new Date().toISOString(),questions:result.questions,correct:result.correct,pct}));track('diagnostic_completed',{metadata:{questions:result.questions,correct:result.correct,pct}});toastSafe(`Diagnóstico concluído · ${pct}% de acertos`);setTimeout(diagnosticCard,80)}return r};wrapped.__gplusV2=true;window.v27NextDrill=wrapped}}
function watchQuestion(){const host=document.getElementById('questionCard')?.parentElement||document.body;const obs=new MutationObserver(()=>addReportButton());obs.observe(host,{subtree:true,childList:true});addReportButton()}
function init(){document.title='Gabarito+ — ENEM & PISM';window.GABARITO_APP=window.GABARITO_APP||{};window.GABARITO_APP.version=V;window.GABARITO_APP.classroomsVersion=CLASSROOM_VERSION;instrument();reportModal();versionBadge();diagnosticCard();watchQuestion();loadClassrooms();track('app_open',{page:localStorage.getItem('study_active_page')||'home',metadata:{version:V,bankSource:window.GABARITO_APP.bankSource||'unknown',bankVersion:window.GABARITO_APP.bankVersion||null}})}
setTimeout(init,180);
})();
