(function(){
'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cfg=window.ESTUDOS_SUPABASE_CONFIG||{};const client=window.supabase?.createClient&&cfg.url&&!/SEU-PROJETO/.test(cfg.url)?window.supabase.createClient(cfg.url,cfg.publishableKey):null;let user=null,profile=null,editing=null,rows=[];
function val(id){return $(id)?.value??''}
async function audit(action,entityId,metadata={}){if(!user)return;await client.from('audit_logs').insert({actor_id:user.id,action,entity_type:'question',entity_id:entityId||null,metadata}).then(()=>{})}
async function guard(){if(!client)throw new Error('Configure js/supabase-config.js antes de usar o painel.');const {data:{user:u},error}=await client.auth.getUser();if(error||!u)throw new Error('Entre na sua conta pelo aplicativo antes de abrir o painel editorial.');user=u;const [{data:p,error:pe},{data:isAdmin,error:ae}]=await Promise.all([client.from('profiles').select('id,display_name').eq('id',u.id).single(),client.rpc('is_current_user_admin')]);if(pe||ae||!isAdmin)throw new Error('Esta conta não possui permissão de administrador.');profile=p}
function qFromForm(){return{id:val('#fId').trim(),exam:val('#fExam'),module:val('#fExam')==='PISM'?(val('#fModule')||'I'):null,area:val('#fArea').trim(),subject:val('#fSubject').trim(),topic:val('#fTopic').trim(),difficulty:val('#fDifficulty'),skill:val('#fSkill').trim(),text:val('#fText').trim(),options:[0,1,2,3,4].map(i=>val('#o'+i).trim()),answer:Number(val('#fAnswer')),editorial_status:val('#fStatus'),explanation:val('#fExplanation').trim(),source:'Painel editorial Gabarito+ 1.1',variant_family:editing?.variant_family||val('#fId').trim(),variant_type:editing?.variant_type||'Personalizada',created_by:user.id,updated_at:new Date().toISOString()}}
function validate(q){const e=[];for(const k of ['id','exam','area','subject','topic','difficulty','skill','text','explanation'])if(!String(q[k]??'').trim())e.push('Campo obrigatório: '+k);if(q.options.some(x=>!x))e.push('Preencha as cinco alternativas.');if(new Set(q.options).size<5)e.push('Há alternativas exatamente duplicadas.');if(q.answer<0||q.answer>4)e.push('Gabarito inválido.');return e}
function open(q=null){editing=q;$('#editor').classList.add('open');$('#editorTitle').textContent=q?`Editar ${q.id}`:'Nova questão';$('#fId').value=q?.id||`CUSTOM-${Date.now()}`;$('#fExam').value=q?.exam||'ENEM';$('#fModule').value=q?.module||'';$('#fArea').value=q?.area||'';$('#fSubject').value=q?.subject||'';$('#fTopic').value=q?.topic||'';$('#fDifficulty').value=q?.difficulty||'Médio';$('#fSkill').value=q?.skill||'';$('#fText').value=q?.text||'';(q?.options||['','','','','']).forEach((x,i)=>$('#o'+i).value=x);$('#fAnswer').value=String(q?.answer??0);$('#fStatus').value=q?.editorial_status||'rascunho';$('#fExplanation').value=q?.explanation||'';$('#disableBtn').style.display=q?'inline-block':'none';$('#disableBtn').textContent=q?.editorial_status==='arquivada'?'Reativar questão':'Arquivar questão'}
async function loadRows(){const term=val('#search').trim(),exam=val('#exam'),area=val('#area'),subject=val('#subject');let q=client.from('questions').select('*').order('updated_at',{ascending:false}).limit(500);if(exam!=='ALL')q=q.eq('exam',exam);if(area!=='ALL')q=q.eq('area',area);if(subject!=='ALL')q=q.eq('subject',subject);if(term)q=q.or(`id.ilike.%${term.replace(/[%(),]/g,'')}%,subject.ilike.%${term.replace(/[%(),]/g,'')}%,topic.ilike.%${term.replace(/[%(),]/g,'')}%,text.ilike.%${term.replace(/[%(),]/g,'')}%`);const {data,error}=await q;if(error)throw error;rows=data||[];renderRows()}
function renderRows(){$('#table').innerHTML=rows.map(q=>`<div class="row ${q.editorial_status==='arquivada'?'disabled-row':''}"><b>${esc(q.id)}</b><span>${esc(q.exam)}</span><span>${q.module?'M'+esc(q.module):'—'}</span><span>${esc(q.area)}</span><span>${esc(q.subject)}</span><span><b>${esc(q.topic)}</b> <small class="status ${esc(q.editorial_status)}">${esc(q.editorial_status)}</small><br><span class="muted">${esc((q.text||'').slice(0,105))}${(q.text||'').length>105?'…':''}</span></span><button data-edit="${esc(q.id)}">Editar</button></div>`).join('')||'<p>Nenhuma questão encontrada.</p>'}
async function stats(){const count=async(filter={})=>{let q=client.from('questions').select('*',{count:'exact',head:true});for(const [k,v]of Object.entries(filter))q=q.eq(k,v);const {count,error}=await q;if(error)throw error;return count||0};const [total,enem,pism,published,draft]=await Promise.all([count(),count({exam:'ENEM'}),count({exam:'PISM'}),count({editorial_status:'publicada'}),count({editorial_status:'rascunho'})]);$('#mTotal').textContent=published;$('#mEnem').textContent=enem;$('#mPism').textContent=pism;$('#mCustom').textContent=Math.max(0,total-3375);$('#hPublished').textContent=published;$('#hReview').textContent=draft;$('#hFamilies').textContent='—';$('#hAlerts').textContent='—';$('#editorialMeta').textContent=`${total} registros no Supabase · ${published} publicados`;const [{count:users},{count:synced},{count:attempts}]=await Promise.all([client.from('profiles').select('*',{count:'exact',head:true}),client.from('progress_state').select('*',{count:'exact',head:true}),client.from('question_attempts').select('*',{count:'exact',head:true})]);$('#v6Users').textContent=users||0;$('#v6Synced').textContent=synced||0;$('#v6Sessions').textContent=attempts||0;$('#v6ServerVersion').textContent='1.1.0'}
async function refreshFilters(){const {data,error}=await client.from('questions').select('area,subject,exam').limit(4000);if(error)return;const exam=val('#exam'),oa=val('#area'),os=val('#subject'),scope=(data||[]).filter(x=>exam==='ALL'||x.exam===exam),areas=[...new Set(scope.map(x=>x.area))].sort((a,b)=>a.localeCompare(b,'pt-BR'));$('#area').innerHTML='<option value="ALL">Todas as áreas</option>'+areas.map(x=>`<option>${esc(x)}</option>`).join('');$('#area').value=areas.includes(oa)?oa:'ALL';const subs=[...new Set(scope.filter(x=>val('#area')==='ALL'||x.area===val('#area')).map(x=>x.subject))].sort((a,b)=>a.localeCompare(b,'pt-BR'));$('#subject').innerHTML='<option value="ALL">Todas as matérias</option>'+subs.map(x=>`<option>${esc(x)}</option>`).join('');$('#subject').value=subs.includes(os)?os:'ALL'}
async function save(){const q=qFromForm(),errors=validate(q);if(errors.length)return alert(errors.join('\n'));const {error}=await client.from('questions').upsert(q,{onConflict:'id'});if(error)return alert(error.message);await audit('question.upsert',q.id,{status:q.editorial_status});$('#editor').classList.remove('open');editing=null;await Promise.all([stats(),loadRows()]);alert('Questão salva no Supabase.')}
async function archive(){if(!editing)return;const status=editing.editorial_status==='arquivada'?'rascunho':'arquivada';const {error}=await client.from('questions').update({editorial_status:status,updated_at:new Date().toISOString()}).eq('id',editing.id);if(error)return alert(error.message);await audit('question.status',editing.id,{status});$('#editor').classList.remove('open');editing=null;await Promise.all([stats(),loadRows()])}
async function loadOps(){const [{data:qa,error:qe},{data:auditRows,error:ae}]=await Promise.all([client.rpc('admin_question_analytics'),client.from('audit_logs').select('*').order('created_at',{ascending:false}).limit(80)]);if(!qe){$('#v6AnalyticsMeta').textContent='Analytics agregados das respostas na nuvem.';$('#v6QuestionAnalytics').innerHTML=(qa||[]).slice(0,30).map(r=>`<div class="v6-qa-row"><b>${esc(r.question_id)}</b><span>${r.wrong} erro(s) em ${r.attempts} tentativa(s)</span><span class="v6-qa-acc ${Number(r.accuracy)<45?'low':''}">${r.accuracy}% acerto</span><span>${r.users} usuário(s)</span></div>`).join('')||'<p class="muted">Sem dados ainda.</p>'}if(!ae)$('#v6AuditList').innerHTML=(auditRows||[]).map(e=>`<div class="v6-audit-row"><span>${new Date(e.created_at).toLocaleString('pt-BR')}</span><b>${esc(e.action)}</b><code>${esc(e.entity_id||'—')}</code></div>`).join('')||'<p class="muted">Sem eventos ainda.</p>'}
async function exportJson(){const {data,error}=await client.from('questions').select('*').order('id').limit(10000);if(error)return alert(error.message);const blob=new Blob([JSON.stringify({version:'1.1.0',exportedAt:new Date().toISOString(),questions:data},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='banco_editorial_gabarito_mais.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),800)}
async function init(){try{await guard();$('#newBtn').onclick=()=>open();$('#closeEditor').onclick=()=>{$('#editor').classList.remove('open');editing=null};$('#saveBtn').onclick=save;$('#duplicateBtn').onclick=()=>{if(!editing)return;open({...editing,id:`CUSTOM-${Date.now()}`,editorial_status:'rascunho'})};$('#disableBtn').onclick=archive;$('#table').onclick=e=>{const id=e.target.dataset.edit;if(id)open(rows.find(x=>String(x.id)===String(id)))};$('#exportBtn').onclick=exportJson;$('#importFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const d=JSON.parse(await f.text()),list=Array.isArray(d.questions)?d.questions:[];if(!list.length)throw new Error('Arquivo sem questions.');for(let i=0;i<list.length;i+=200){const {error}=await client.from('questions').upsert(list.slice(i,i+200),{onConflict:'id'});if(error)throw error}await audit('questions.import',null,{count:list.length});await Promise.all([stats(),loadRows()]);alert(`${list.length} questões importadas.`)}catch(err){alert(err.message)}e.target.value=''};['search','exam','area','subject'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',async()=>{if(id==='exam'||id==='area')await refreshFilters();await loadRows()}));$('#fExam').addEventListener('change',()=>{$('#fModule').disabled=val('#fExam')!=='PISM'});$('#v6RefreshAudit').onclick=loadOps;$('#v6RefreshAnalytics').onclick=loadOps;await refreshFilters();await Promise.all([stats(),loadRows(),loadOps()])}catch(e){document.querySelector('main').innerHTML=`<section class="panel"><h2>Acesso ao painel indisponível</h2><p>${esc(e.message)}</p><p>Entre no aplicativo com uma conta admin e tente novamente.</p><a href="index.html">Voltar ao aplicativo</a></section>`}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
