(function(){
'use strict';
const VERSION='2.2.0';
const DISC_KEY='gplus_discursive_progress_v22';
const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
function ensureMeta(){document.title='Gabarito+ — ENEM & PISM';document.documentElement.lang='pt-BR';const canonical='https://gabarito-mais.vercel.app/app';let link=$('link[rel="canonical"]');if(!link){link=document.createElement('link');link.rel='canonical';document.head.appendChild(link)}link.href=canonical;const meta=(key,value,property=false)=>{let el=$(property?`meta[property="${key}"]`:`meta[name="${key}"]`);if(!el){el=document.createElement('meta');el.setAttribute(property?'property':'name',key);document.head.appendChild(el)}el.content=value};meta('description','Plataforma de estudos para ENEM e PISM com questões, revisão, simulados, redação e orientação baseada no seu histórico.');meta('og:title','Gabarito+ — ENEM & PISM',true);meta('og:description','Estude com direção: pratique, revise seus erros e entenda o próximo passo.',true);meta('og:type','website',true);meta('og:url',canonical,true);meta('og:image','https://gabarito-mais.vercel.app/assets/icons/icon-512.png',true);meta('twitter:card','summary')}
function humanize(id){return String(id||'Campo').replace(/^v\d+/i,'').replace(/([a-z])([A-Z])/g,'$1 $2').replace(/[-_]+/g,' ').trim().replace(/^./,c=>c.toUpperCase())}
function ensureA11y(){$$('input,select,textarea').forEach(el=>{if(el.getAttribute('aria-label')||el.getAttribute('aria-labelledby'))return;const id=el.id;const label=id?document.querySelector(`label[for="${CSS.escape(id)}"]`):null;if(label)return;const name=el.placeholder||el.name||humanize(id);if(name)el.setAttribute('aria-label',name)});$$('[role="dialog"],.modal,.v5-modal,#v5AccountModal').forEach(dialog=>{$$('button',dialog).forEach(btn=>{if(btn.getAttribute('aria-label'))return;const txt=(btn.textContent||'').trim().toLowerCase();const icon=btn.querySelector('[data-lucide="x"],[data-lucide="x-circle"],[data-lucide="circle-x"]');if(icon||txt==='×'||txt==='x')btn.setAttribute('aria-label','Fechar')})});const main=$('main');if(main&&!main.id)main.id='mainContent'}
function replaceText(root,from,to){if(!root)return;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(n=>{if(n.nodeValue&&n.nodeValue.includes(from))n.nodeValue=n.nodeValue.split(from).join(to)})}
function cleanImplementationLanguage(){const foot=$('.sidebar-foot strong');if(foot)foot.textContent='Gabarito+';const bank=$('#v7BankSource');if(bank&&/Banco local|Cloud|Supabase/i.test(bank.textContent||''))bank.textContent='Conteúdo disponível neste dispositivo';const onboarding=$('#v37Onboarding');if(onboarding){replaceText(onboarding,'Nuvem, sincronização e banco Supabase','Progresso, sincronização e conteúdo de estudo');replaceText(onboarding,'Radar de Aprovação','priorização do estudo')}const modal=$('#v5AccountModal');if(modal){replaceText(modal,'Conta Supabase','Conta e sincronização');replaceText(modal,'Supabase','sincronização');replaceText(modal,'Usar servidor','Sincronizar com minha conta');replaceText(modal,'Usar este dispositivo','Manter neste dispositivo');if(!$('#v22SyncNote',modal)){const note=document.createElement('p');note.id='v22SyncNote';note.className='v22-sync-note';note.textContent='Sem entrar na conta, seu progresso fica salvo neste dispositivo. Ao entrar, a sincronização entre dispositivos fica disponível.';const anchor=modal.querySelector('h2,h3,.modal-title,.v5-account-title');anchor?.insertAdjacentElement('afterend',note)}}}
function getStats(){try{return typeof window.totalQStats==='function'?window.totalQStats():{answered:0,correct:0}}catch{return{answered:0,correct:0}}}
function getRanking(){try{return typeof window.rankSubjects==='function'?window.rankSubjects():[]}catch{return[]}}
function confidence(n){if(n<10)return{label:'Inicial',text:'Ainda há pouca amostra. Use a recomendação como ponto de partida, não como conclusão.'};if(n<30)return{label:'Em construção',text:'Já existem sinais úteis, mas o diagnóstico ainda pode mudar com novas respostas.'};return{label:'Mais consistente',text:'A recomendação usa uma amostra maior do seu histórico recente.'}}
function renderGuidance(){const home=$('#v39Home');if(!home)return;let card=$('#v22Guidance',home);if(!card){card=document.createElement('section');card.id='v22Guidance';card.className='card v22-guidance';const hero=$('.v39-hero',home);hero?.insertAdjacentElement('afterend',card)}const st=getStats(),rank=getRanking(),top=rank[0],c=confidence(Number(st.answered)||0),accuracy=st.answered?Math.round((Number(st.correct)||0)/st.answered*100):null;const focus=top?.subject||'gere sua primeira amostra';const reason=top?`O plano prioriza ${esc(focus)} porque combina aproveitamento, erros e tempo estudado dentro da sua rota atual.`:'Responda algumas questões e registre sessões de estudo para o Gabarito+ começar a ordenar suas prioridades.';card.innerHTML=`<div class="v22-guidance-head"><div><span class="v22-kicker">Orientação explicável</span><h3>Por que este é o próximo passo?</h3></div><span class="v22-confidence">Confiança: ${esc(c.label)}</span></div><p>${reason}</p><div class="v22-evidence"><span><b>${Number(st.answered)||0}</b> respostas usadas</span><span><b>${accuracy==null?'—':accuracy+'%'}</b> acerto acumulado</span><span><b>${esc(focus)}</b> prioridade atual</span></div><p class="v22-limit">${esc(c.text)} O Gabarito+ não prevê aprovação nem transforma dificuldade editorial em estatística populacional.</p>`}
function allQuestions(){try{return window.QuestionBank?.getAll?.()||[]}catch{return[]}}
function currentQuestion(){const text=$('#questionCard .q-text')?.textContent?.trim();if(!text)return null;return allQuestions().find(q=>String(q.text||'').trim()===text)||null}
function renderQuestionTrust(){const card=$('#questionCard');if(!card)return;const q=currentQuestion();if(!q)return;if(card.dataset.v22QuestionId===String(q.id)&&$('.v22-question-trust',card))return;card.dataset.v22QuestionId=String(q.id);$('.v22-question-trust',card)?.remove();let personal=null;try{personal=typeof window.qstats==='function'?window.qstats()[q.id]:null}catch{}const type=/oficial/i.test(String(q.variantType||q.source||''))?'Oficial':/autoral/i.test(String(q.variantType||q.source||''))?'Autoral':'Curada';const attempts=Number(personal?.attempts)||0,correct=Number(personal?.correct)||0,rate=attempts?Math.round(correct/attempts*100):null;const trust=document.createElement('div');trust.className='v22-question-trust';trust.innerHTML=`<div class="v22-trust-grid"><span><small>Tipo</small><b>${esc(type)}</b></span><span><small>Referência</small><b>${esc(q.source||'Banco Gabarito+')}</b></span><span><small>Habilidade</small><b>${esc(q.skill||q.topic||'Não registrada')}</b></span><span><small>Dificuldade</small><b>${esc(q.difficulty||'Não registrada')}</b></span></div><p>${attempts?`No seu histórico: ${attempts} tentativa${attempts===1?'':'s'} e ${rate}% de acerto.`:'Você ainda não tem amostra pessoal suficiente nesta questão.'} A dificuldade exibida é editorial; não é uma estimativa estatística de todos os candidatos.</p>`;card.appendChild(trust)}
function readDisc(){try{return JSON.parse(localStorage.getItem(DISC_KEY)||'{}')}catch{return{}}}
function writeDisc(v){localStorage.setItem(DISC_KEY,JSON.stringify(v))}
function discursiveSource(prompt){return (window.PISM_DISCURSIVE||[]).find(x=>String(x.prompt||'').trim()===String(prompt||'').trim())}
function renderDiscSummary(list){let summary=$('#v22DiscSummary',list);const state=readDisc(),rows=Object.values(state),rated=rows.filter(x=>Number.isFinite(Number(x.score)));if(!summary){summary=document.createElement('div');summary.id='v22DiscSummary';summary.className='card v22-disc-summary';list.prepend(summary)}summary.innerHTML=`<strong>Treino discursivo salvo</strong><span>${rows.length} resposta${rows.length===1?'':'s'} salva${rows.length===1?'':'s'}${rated.length?` · autoavaliação média ${Math.round(rated.reduce((a,x)=>a+Number(x.score),0)/rated.length)}%`:''}</span>`}
function enhanceDiscursives(){const list=$('#discursiveList');if(!list)return;const state=readDisc();$$('.card.discursive',list).forEach(card=>{if(card.dataset.v22Enhanced==='1')return;const prompt=$('h4',card)?.textContent?.trim(),item=discursiveSource(prompt);if(!item)return;card.dataset.v22Enhanced='1';const textarea=$('textarea',card);const saved=state[item.id]||{};if(textarea){textarea.value=saved.answer||'';textarea.setAttribute('aria-label',`Resposta discursiva de ${item.subject||'PISM'}`)}const oldRubric=$('.rubric',card);if(oldRubric)oldRubric.style.display='none';const box=document.createElement('div');box.className='v22-disc-tools';const checks=(Array.isArray(item.rubric)?item.rubric:[]).map((r,i)=>`<label><input type="checkbox" data-rubric="${i}" ${saved.criteria?.includes(i)?'checked':''}> <span>${esc(r)}</span></label>`).join('');const model=item.modelAnswer||item.referenceAnswer||item.answerModel||null;box.innerHTML=`<div class="v22-disc-head"><strong>Autocorreção guiada</strong><span id="v22Score-${esc(item.id)}">${Number.isFinite(Number(saved.score))?Number(saved.score)+'%':'Não avaliada'}</span></div><div class="v22-rubric-checks">${checks||'<span class="muted">Critérios editoriais ainda não cadastrados.</span>'}</div><div class="v22-disc-actions"><button type="button" class="btn btn-sm btn-primary" data-save>Salvar resposta</button>${model?'<button type="button" class="btn btn-sm btn-secondary" data-model>Ver resposta de referência</button>':''}</div>${model?`<div class="v22-model" hidden>${esc(model)}</div>`:'<p class="v22-model-note">Resposta de referência ainda não publicada. O Gabarito+ não improvisa um modelo sem revisão editorial.</p>'}`;card.appendChild(box);const recalc=()=>{const inputs=$$('input[data-rubric]',box),checked=inputs.filter(x=>x.checked);const score=inputs.length?Math.round(checked.length/inputs.length*100):null;const out=$(`#v22Score-${CSS.escape(String(item.id))}`,box);if(out)out.textContent=score==null?'Não avaliada':score+'%';return{score,criteria:checked.map(x=>Number(x.dataset.rubric))}};$$('input[data-rubric]',box).forEach(x=>x.addEventListener('change',recalc));$('[data-save]',box)?.addEventListener('click',()=>{const s=readDisc(),r=recalc();s[item.id]={answer:textarea?.value||'',score:r.score,criteria:r.criteria,updatedAt:new Date().toISOString()};writeDisc(s);renderDiscSummary(list);if(typeof window.toast==='function')window.toast('Resposta discursiva salva')});$('[data-model]',box)?.addEventListener('click',()=>{const modelBox=$('.v22-model',box);if(modelBox)modelBox.hidden=!modelBox.hidden})});renderDiscSummary(list)}
function installObservers(){const q=$('#questionCard');if(q){new MutationObserver(()=>queueMicrotask(renderQuestionTrust)).observe(q,{childList:true,subtree:true});renderQuestionTrust()}const d=$('#discursiveList');if(d){new MutationObserver(()=>{if($('.card.discursive:not([data-v22-enhanced="1"])',d))queueMicrotask(enhanceDiscursives)}).observe(d,{childList:true});enhanceDiscursives()}['#v39Questions','#v39Weak','#v39MainText'].forEach(sel=>{const el=$(sel);if(el)new MutationObserver(()=>queueMicrotask(renderGuidance)).observe(el,{childList:true,characterData:true,subtree:true})});renderGuidance()}
function init(){try{ensureMeta();ensureA11y();cleanImplementationLanguage();renderGuidance();installObservers();document.body.classList.add('v22-quality');window.GABARITO_APP=window.GABARITO_APP||{};window.GABARITO_APP.qualityLayer=VERSION}catch(e){console.warn('[Gabarito+] Camada de qualidade indisponível:',e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
