(function(){
'use strict';
const VERSION='2.1.0';
const DISC_KEY='gplus_discursive_progress_v3';
const safeParse=(raw,fallback)=>{try{return JSON.parse(raw)}catch{return fallback}};
const escText=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmtDate=v=>{if(!v)return 'não informada';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString('pt-BR')};
function ensureMeta(selector,attrs){let el=document.head.querySelector(selector);if(!el){el=document.createElement('meta');document.head.appendChild(el)}for(const [k,v] of Object.entries(attrs))el.setAttribute(k,v);return el}
function fixMetadata(){
 document.title='Gabarito+ — ENEM & PISM';
 let canonical=document.head.querySelector('link[rel="canonical"]');if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.appendChild(canonical)}canonical.href='https://gabarito-mais.vercel.app/app';
 ensureMeta('meta[property="og:title"]',{property:'og:title',content:'Gabarito+ — ENEM & PISM'});
 ensureMeta('meta[property="og:description"]',{property:'og:description',content:'Plano personalizado, questões, revisão espaçada, simulados e redação para ENEM e PISM.'});
 ensureMeta('meta[property="og:url"]',{property:'og:url',content:'https://gabarito-mais.vercel.app/app'});
 ensureMeta('meta[property="og:image"]',{property:'og:image',content:'https://gabarito-mais.vercel.app/assets/icons/icon-512.png'});
 ensureMeta('meta[property="og:type"]',{property:'og:type',content:'website'});
 ensureMeta('meta[name="twitter:card"]',{name:'twitter:card',content:'summary'});
}
function associateLabels(){
 document.querySelectorAll('label:not([for])').forEach(label=>{const control=label.querySelector('input,select,textarea')||label.nextElementSibling;if(control&&/^(INPUT|SELECT|TEXTAREA)$/.test(control.tagName)){if(!control.id)control.id='gplus-field-'+Math.random().toString(36).slice(2,9);label.htmlFor=control.id}});
 document.querySelectorAll('button.icon-btn').forEach(btn=>{if(btn.getAttribute('aria-label'))return;const text=(btn.textContent||'').trim();if(!text)btn.setAttribute('aria-label','Ação')});
 const close=document.querySelector('#v5AccountModal .v5-account-head .icon-btn');if(close)close.setAttribute('aria-label','Fechar conta e sincronização');
 const deletePw=document.getElementById('v6DeletePassword');if(deletePw&&!deletePw.getAttribute('aria-label'))deletePw.setAttribute('aria-label','Senha atual para excluir a conta');
 const accountTitle=document.getElementById('v5AccountTitle');if(accountTitle)accountTitle.textContent='Conta e sincronização';
 const onboardingSub=document.querySelector('.v37-onboarding-brand span');if(onboardingSub)onboardingSub.textContent='Plano personalizado e sincronização opcional';
 const sideFoot=document.querySelector('.sidebar-foot strong');if(sideFoot)sideFoot.textContent='Progresso e conteúdo';
}
function totalAttempts(){try{return Object.values(typeof qstats==='function'?qstats():safeParse(localStorage.getItem('study_question_stats_v2')||'{}',{})).reduce((n,x)=>n+Number(x?.attempts||0),0)}catch{return 0}}
function confidenceInfo(n){if(n<10)return{level:'Inicial',pct:24,copy:'Poucos dados. O app evita conclusões fortes e prioriza diagnóstico.'};if(n<30)return{level:'Em construção',pct:58,copy:'Já existe sinal útil, mas a recomendação ainda pode mudar rapidamente.'};return{level:'Mais consistente',pct:86,copy:'A amostra já permite priorizações mais estáveis, sem prometer nota futura.'}}
function bankCounts(){const all=Array.isArray(window.QUESTIONS)?window.QUESTIONS:(typeof QUESTIONS!=='undefined'?QUESTIONS:[]);const count=(exam,module)=>all.filter(q=>q.exam===exam&&(!module||String(q.module)===String(module))).length;return{total:all.length,enem:count('ENEM'),p1:count('PISM','I'),p2:count('PISM','II'),p3:count('PISM','III')}}
function guidanceData(){
 const attempts=totalAttempts(),conf=confidenceInfo(attempts),exam=window.app?.settings?.focusExam||'ENEM';let priority='Diagnóstico inicial',reason='Responda questões do vestibular em foco para criar uma amostra real.';
 try{const ranked=typeof rankSubjects==='function'?rankSubjects():[];if(ranked?.length){priority=ranked[0].subject;const p=ranked[0];reason=`${priority} sobe na prioridade por combinar ${Math.round((1-p.rate)*100)}% de margem de melhora, erros registrados e tempo estudado.`}}
 catch(_){ }
 let days=null;try{const target=exam==='ENEM'?app.settings.enemDate:app.settings.pismDate;days=typeof dateDiff==='function'?dateDiff(target):null}catch(_){ }
 return{attempts,conf,exam,priority,reason,days};
}
function renderTrustHome(){
 const host=document.getElementById('v39Home');if(!host)return;let el=document.getElementById('gplusTrustHome');if(!el){el=document.createElement('section');el.id='gplusTrustHome';el.className='gplus-trust-home';const diag=document.getElementById('gplusV2Diagnostic');(diag||host.querySelector('.v39-hero'))?.insertAdjacentElement('afterend',el)||host.prepend(el)}
 const d=guidanceData(),b=bankCounts();
 el.innerHTML=`<div class="gplus-trust-head"><div><span class="gplus-trust-kicker">Orientação explicável</span><h3>Por que o Gabarito+ está recomendando isso?</h3><p>Sem algoritmo mágico: a prioridade usa seu desempenho, erros, revisões, tempo de estudo e prova em foco.</p></div><div class="gplus-confidence"><span>Confiança da recomendação</span><strong>${d.conf.level}</strong><div class="gplus-confidence-track"><i style="width:${d.conf.pct}%"></i></div><small>${d.conf.copy}</small></div></div><div class="gplus-trust-grid"><div><span>Prioridade atual</span><strong>${escText(d.priority)}</strong><small>${escText(d.reason)}</small></div><div><span>Amostra usada</span><strong>${d.attempts} tentativa${d.attempts===1?'':'s'}</strong><small>${d.days==null?'A data da prova entra no cálculo quando configurada.':`${Math.max(0,d.days)} dias até a prova configurada.`}</small></div><div><span>Banco disponível</span><strong>${b.total.toLocaleString('pt-BR')} itens</strong><small>ENEM ${b.enem.toLocaleString('pt-BR')} · PISM I ${b.p1.toLocaleString('pt-BR')} · II ${b.p2.toLocaleString('pt-BR')} · III ${b.p3.toLocaleString('pt-BR')}</small></div></div><details class="gplus-method"><summary>Ver metodologia e limites</summary><div class="gplus-method-body"><p><b>1. Diagnóstico:</b> amostras pequenas recebem baixa confiança e não viram conclusão definitiva.</p><p><b>2. Prioridade:</b> assuntos com menor aproveitamento, erros recorrentes e pouca cobertura sobem na fila.</p><p><b>3. Recuperação:</b> erros retornam em revisão; acertar novamente é tratado como evidência de recuperação.</p><p><b>4. Limite:</b> os indicadores organizam o estudo. Eles não estimam nota oficial nem garantem aprovação.</p><p><b>Transparência editorial:</b> o app não atribui revisor, data de revisão ou status “oficial” quando esses dados não estão cadastrados no item.</p></div></details>`;
}
function questionType(q){const t=String(q?.variantType||q?.variant_type||'');if(/oficial/i.test(t))return'Questão oficial declarada';if(/autoral/i.test(t))return'Questão autoral';return'Origem não declarada'}
function ownDifficulty(q){let st=null;try{st=typeof qstats==='function'?qstats()[q.id]:null}catch(_){ }if(!st||!st.attempts)return'Você ainda não gerou evidência nesta questão';const rate=(st.correct||0)/Math.max(1,st.attempts||0);if(st.attempts<2)return'1 tentativa — cedo para classificar';if(rate>=.75)return'Baixa para você até agora';if(rate>=.4)return'Moderada para você até agora';return'Alta para você até agora'}
function addQuestionTrust(){
 const card=document.getElementById('questionCard'),q=window.app?.currentQuestion;if(!card||!q)return;card.querySelector('.gplus-question-trust')?.remove();const box=document.createElement('div');box.className='gplus-question-trust';const reviewed=q.reviewedAt||q.reviewed_at||q.lastReviewed||q.last_reviewed_at;const reviewer=q.reviewer||q.reviewer_name||q.reviewedBy;box.innerHTML=`<div class="gplus-qtrust-top"><strong>Ficha de confiança da questão</strong><span>${escText(questionType(q))}</span></div><div class="gplus-qtrust-grid"><div><small>Referência pedagógica</small><b>${escText(q.source||'não informada')}</b></div><div><small>Habilidade</small><b>${escText(q.skill||'não informada')}</b></div><div><small>Dificuldade editorial</small><b>${escText(q.difficulty||'não informada')}</b></div><div><small>Sua evidência</small><b>${escText(ownDifficulty(q))}</b></div><div><small>Última revisão</small><b>${escText(fmtDate(reviewed))}</b></div><div><small>Responsável pela revisão</small><b>${escText(reviewer||'não informado')}</b></div></div><p class="gplus-qtrust-note">A dificuldade editorial é um rótulo do banco. O Gabarito+ não a apresenta como dificuldade estatística da população sem dados agregados suficientes.</p>`;const toolbar=card.querySelector('.q-toolbar');toolbar?.insertAdjacentElement('beforebegin',box)||card.appendChild(box);
 const fb=card.querySelector('#qFeedback');if(fb?.dataset.done==='1'&&!fb.querySelector('.gplus-feedback-limit')){const note=document.createElement('div');note.className='gplus-feedback-limit';note.textContent='A explicação mostra a justificativa cadastrada. Quando os distratores não possuem justificativa individual revisada, o app não inventa uma.';fb.appendChild(note)}
}
function discId(x,index){let h=2166136261,s=`${x.module}|${x.subject}|${x.topic}|${x.prompt}|${index}`;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return'disc_'+(h>>>0).toString(36)}
function discLoad(){return safeParse(localStorage.getItem(DISC_KEY)||'{}',{})}
function discSave(all){localStorage.setItem(DISC_KEY,JSON.stringify(all))}
function discSummary(progress,arr){const ids=arr.map((x,i)=>discId(x,i));const rows=ids.map(id=>progress[id]).filter(Boolean),answered=rows.filter(r=>String(r.answer||'').trim()).length,scored=rows.filter(r=>Number.isFinite(r.score)),avg=scored.length?Math.round(scored.reduce((n,r)=>n+r.score,0)/scored.length):0;return{answered,avg,scored:scored.length}}
function renderDiscursiveV3(){
 const sel=document.getElementById('discModule'),host=document.getElementById('discursiveList');if(!sel||!host||!Array.isArray(window.PISM_DISCURSIVE))return;const mod=sel.value,arr=window.PISM_DISCURSIVE.filter(x=>mod==='ALL'||String(x.module)===String(mod)),progress=discLoad(),sum=discSummary(progress,arr);
 host.innerHTML=`<div class="gplus-disc-summary"><div><span>Respostas salvas</span><strong>${sum.answered}/${arr.length}</strong></div><div><span>Média da autoavaliação</span><strong>${sum.scored?sum.avg+'%':'—'}</strong></div><p>A pontuação abaixo é uma <b>autoavaliação por critérios</b>, não uma correção oficial.</p></div>`+arr.map((x,i)=>{const id=discId(x,i),p=progress[id]||{},rub=Array.isArray(x.rubric)?x.rubric:[],checks=Array.isArray(p.checks)?p.checks:[],reference=x.modelAnswer||x.model_answer||x.referenceAnswer||x.reference_answer||'';return`<article class="card discursive gplus-disc" data-disc-id="${id}"><div class="q-meta"><span class="tag pism">PISM</span><span class="tag">Módulo ${escText(x.module)}</span><span class="tag">${escText(x.subject)}</span><span class="tag">${escText(x.topic)}</span><span class="tag">Autoral</span></div><h4>${escText(x.prompt)}</h4><label class="gplus-disc-label" for="${id}-answer">Sua resposta</label><textarea id="${id}-answer" class="field gplus-disc-answer" placeholder="Escreva sua resposta completa...">${escText(p.answer||'')}</textarea><div class="gplus-disc-actions"><button type="button" class="btn btn-sm btn-primary" data-disc-save="${id}">Salvar resposta</button><span class="gplus-disc-saved" id="${id}-saved">${p.updatedAt?'Salva em '+fmtDate(p.updatedAt):'Ainda não salva'}</span></div><div class="gplus-disc-rubric"><strong>Critérios de autocorreção</strong>${rub.map((r,j)=>`<label><input type="checkbox" data-disc-check="${id}" data-index="${j}" ${checks[j]?'checked':''}><span>${escText(r)}</span></label>`).join('')}<div class="gplus-disc-score">Autoavaliação: <b id="${id}-score">${Number.isFinite(p.score)?p.score:0}%</b></div></div><details class="gplus-disc-reference"><summary>Comparar com resposta de referência</summary>${reference?`<p>${escText(reference)}</p>`:`<p><b>Resposta de referência ainda não publicada para este item.</b> O Gabarito+ não gera uma resposta-modelo improvisada sem revisão editorial.</p>`}</details></article>`}).join('');
 host.querySelectorAll('[data-disc-save]').forEach(btn=>btn.addEventListener('click',()=>saveDiscCard(btn.dataset.discSave)));
 host.querySelectorAll('[data-disc-check]').forEach(ch=>ch.addEventListener('change',()=>scoreDiscCard(ch.dataset.discCheck)));
}
function saveDiscCard(id){const card=document.querySelector(`[data-disc-id="${id}"]`);if(!card)return;const all=discLoad(),answer=card.querySelector('.gplus-disc-answer')?.value||'',checks=[...card.querySelectorAll('[data-disc-check]')].map(x=>x.checked),score=checks.length?Math.round(checks.filter(Boolean).length/checks.length*100):0;all[id]={...(all[id]||{}),answer,checks,score,updatedAt:new Date().toISOString()};discSave(all);const saved=document.getElementById(id+'-saved');if(saved)saved.textContent='Salva agora';const scoreEl=document.getElementById(id+'-score');if(scoreEl)scoreEl.textContent=score+'%';if(typeof toast==='function')toast('Resposta discursiva salva')}
function scoreDiscCard(id){const card=document.querySelector(`[data-disc-id="${id}"]`);if(!card)return;const all=discLoad(),checks=[...card.querySelectorAll('[data-disc-check]')].map(x=>x.checked),score=checks.length?Math.round(checks.filter(Boolean).length/checks.length*100):0;all[id]={...(all[id]||{}),answer:card.querySelector('.gplus-disc-answer')?.value||'',checks,score,updatedAt:new Date().toISOString()};discSave(all);const scoreEl=document.getElementById(id+'-score');if(scoreEl)scoreEl.textContent=score+'%'}
function wrap(name,after){const base=window[name];if(typeof base!=='function'||base.__gplusTrust)return;const wrapped=function(...args){const out=base.apply(this,args);try{after(...args)}catch(e){console.warn('[Gabarito+] trust layer:',e)}return out};wrapped.__gplusTrust=true;window[name]=wrapped}
function install(){
 fixMetadata();associateLabels();renderTrustHome();
 wrap('renderDashboard',()=>renderTrustHome());wrap('generatePlan',()=>renderTrustHome());wrap('renderQuestion',()=>addQuestionTrust());wrap('answerQuestion',()=>setTimeout(addQuestionTrust,0));wrap('setFocusExam',()=>setTimeout(renderTrustHome,0));
 if(typeof window.renderDiscursive==='function'){window.renderDiscursive=renderDiscursiveV3;window.renderDiscursive.__gplusTrust=true}
 const obs=new MutationObserver(()=>{associateLabels();if(document.getElementById('questionCard')?.children.length)addQuestionTrust()});obs.observe(document.body,{childList:true,subtree:true});
 if(document.getElementById('page-mocks')?.classList.contains('active'))renderDiscursiveV3();
 window.GABARITO_APP=window.GABARITO_APP||{};window.GABARITO_APP.trustVersion=VERSION;
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,0),{once:true});else setTimeout(install,0);
})();
