import assert from 'node:assert/strict';
import {chromium} from 'playwright';
const base=process.env.BASE_URL||'http://127.0.0.1:3090';
const browser=await chromium.launch({headless:true});
try{
  const page=await browser.newPage();
  const pageErrors=[];page.on('pageerror',e=>pageErrors.push(e.message));
  await page.goto(base+'/index.html',{waitUntil:'domcontentloaded',timeout:20000});
  await page.waitForFunction(()=>window.GABARITO_APP?.ready===true,{timeout:15000});
  assert.equal(await page.locator('#v7Boot').count(),0,'overlay de boot permaneceu na tela');
  assert.equal(await page.title(),'Gabarito+ — ENEM & PISM');
  assert.equal(await page.evaluate(()=>window.GABARITO_APP?.qualityLayer),'2.2.0');
  assert.equal(await page.evaluate(()=>window.GABARITO_ARCHIVED_QUESTION_IDS?.length),58);
  await page.evaluate(()=>window.go('questions'));
  await page.waitForSelector('#page-questions.active',{timeout:5000});
  await page.waitForSelector('#questionCard .q-text',{timeout:5000});
  await page.waitForSelector('#questionCard .v22-question-trust',{timeout:5000});
  await page.evaluate(()=>window.go('mocks'));
  await page.waitForSelector('#discursiveList .card.discursive textarea',{timeout:5000});
  await page.waitForSelector('#v22DiscSummary',{timeout:5000});
  const input=page.locator('#discursiveList .card.discursive textarea').first();await input.fill('Resposta de teste automatizado.');
  const save=page.locator('#discursiveList .card.discursive [data-save]').first();await save.click();
  assert.match(await page.evaluate(()=>localStorage.getItem('gplus_discursive_progress_v22')||''),/Resposta de teste automatizado/);
  await page.goto(base+'/landing-clean.html',{waitUntil:'domcontentloaded',timeout:10000});
  assert.match(await page.title(),/ENEM e PISM/);
  assert.equal(await page.locator('link[rel="canonical"]').getAttribute('href'),'https://gabarito-mais.vercel.app/');
  assert.equal(await page.locator('#metodologia').count(),1);
  assert.equal(await page.locator('#editorial').count(),1);
  if(pageErrors.length)throw new Error('Erros no navegador: '+pageErrors.join(' | '));
}finally{await browser.close()}
